package main

import (
	"testing"
)

func TestIstPalindrom(t *testing.T) {
	richtige := [...]string{
		"",
		"A",
		"Anna",
		"Bob",
		"Bub",
		"Dioid",
		"Ebbe",
		"Egge",
		"Gag",
		"Hannah",
		"Lagerregal",
		"Level",
		"Madam",
		"Monom",
		"Neffen",
		"Otto",
		"Pep",
		"Radar",
		"Regallager",
		"Reittier",
		"Reliefpfeiler",
		"Rentner",
		"Testset",
		"Retsinakanister",
		"Ein Eis esse sie nie",
		"Vitaler Leben - Nebel relativ",
		"Able was I ere I saw Elba",
	}
	falsche := [...]string{
		"Ob",
		"Tieflieger",
		"Golang",
		"Donaudampfschiffahrtsgesellschaft",
		"Abbruchbedingung",
		"Abschlusszeichen",
		"Additionsoperator",
		"Adresse",
		"Adressoperator",
		"Anweisung",
		"Argument",
		"Array",
		"Ausdruck",
		"Auswertung",
		"Auswertungsreihenfolge",
		"Bezeichner",
		"Block",
		"Blockkommentar",
		"Boolean",
		"Datentyp",
		"Deklaration",
		"Deklarationsoperator",
		"Dereferenzierung",
		"Dereferenzierungsoperator",
		"Dezimalzahl",
		"Divisionsoperator",
		"Ellipse",
		"Endlosschleife",
		"Ergebnistyp",
		"Exponent",
		"Flag",
		"Funktionsdeklaration",
		"Funktionsrumpf",
		"Funktionsaufruf",
		"Funktionsdeklaration",
		"Genauigkeit",
		"Gleichheitsoperator",
		"Gleitkommazahlen",
		"Hexadezimalzahl",
		"Index",
		"Infixnotation",
		"Klammerung",
		"Konkatenationsoperator",
		"Konstante",
		"Konstantendeklaration",
		"Laufvariable",
		"Lebenszeit",
		"Leerraum",
		"Mantisse",
		"Matrix",
		"Mindestbreite",
		"Multiplikationsoperator",
		"Nachkommastellen",
		"Negationsoperator",
		"Normalisierung",
		"Oktalzahl",
		"Operator",
		"Paket",
		"Paketklausel",
		"Parameter",
		"Parameterdeklaration",
		"Programmelemente",
		"Referenzen",
		"Rundungsfehler",
		"Schleife",
		"Schleifenbedingung",
		"Schleifendurchlauf",
		"Schleifenrumpf",
		"Seiteneffekt",
		"Semikolon",
		"Separatorzeichen",
		"Sichtbarkeit",
		"Signatur",
		"Speicheradresse",
		"Speicherleck",
		"Standardformat",
		"Standardtyp",
		"String",
		"Substring",
		"Subtraktionsoperator",
		"Teilausdruck",
		"Typanpassung",
		"Typkonvertierung",
		"Ungleichheitsoperator",
		"Variable",
		"Variablendeklaration",
		"Verben",
		"Vergleichsoperatoren",
		"Vorzeichen",
		"Wert",
		"whitespace",
		"Wiederholungsanweisung",
		"Zeichenkette",
		"Zeiger",
		"Zeilenkommentar",
		"Zuweisung",
		"Zuweisungsoperator",
		"Zweierkomplement",
	}
	for _, v := range richtige {
		if !istPalindrom(v) {
			t.Errorf("istPalindrom(%v) = %v, want %v", v, false, true)
		}
	}

	for _, v := range falsche {
		if istPalindrom(v) {
			t.Errorf("istPalindrom(%v) = %v, want %v", v, true, false)
		}
	}
}
