package main

import (
	"testing"
)

func TestEncrypt(t *testing.T) {
	tests := [...]struct {
		m    string
		d    int
		want string
	}{
		{"EINEGEHEIMEBOTSCHAFT", 1, "EINEGEHEIMEBOTSCHAFT"},
		{"EINEGEHEIMEBOTSCHAFT", 2, "EEIBNOETGSECHHEAIFMT"},
		{"EINEGEHEIMEBOTSCHAFT", 4, "EEECIHBHNEOAEITFGMST"},
		{"EINEGEHEIMEBOTSCHAFT", 5, "EGIOHIEMTANHESFEEBCT"},
		{"EINEGEHEIMEBOTSCHAFT", 10, "ENGHIEOSHFIEEEMBTCAT"},
		{"0123", 1, "0123"},
		{"0123", 2, "0213"},
		{"0123", 4, "0123"},
		{"012345", 1, "012345"},
		{"012345", 2, "031425"},
		{"012345", 3, "024135"},
		{"012345", 6, "012345"},
		{"01234567", 1, "01234567"},
		{"01234567", 2, "04152637"},
		{"01234567", 4, "02461357"},
		{"01234567", 8, "01234567"},
		{"012345678", 1, "012345678"},
		{"012345678", 3, "036147258"},
		{"012345678", 9, "012345678"},
		{"0123456789", 1, "0123456789"},
		{"0123456789", 2, "0516273849"},
		{"0123456789", 5, "0246813579"},
		{"0123456789", 10, "0123456789"},
		{"TIEFLIEGER", 1, "TIEFLIEGER"},
		{"TIEFLIEGER", 2, "TIIEEGFELR"},
		{"TIEFLIEGER", 5, "TELEEIFIGR"},
		{"TIEFLIEGER", 10, "TIEFLIEGER"},
		{"VARIABLENDEKLARATION", 2, "VEAKRLIAARBALTEINODN"},
		{"VARIABLENDEKLARATION", 4, "VBEAALKTRELIINAOADRN"},
		{"VARIABLENDEKLARATION", 5, "VANLTABDAIRLEROIEKAN"},
		{"VARIABLENDEKLARATION", 10, "VRALNELRTOAIBEDKAAIN"},
		{"SCHLEIFENBEDINGUNG", 2, "SBCEHDLIENIGFUENNG"},
		{"SCHLEIFENBEDINGUNG", 3, "SFICENHNGLBUEENIDG"},
		{"SCHLEIFENBEDINGUNG", 6, "SLFBIUCEEENNHINDGG"},
		{"SCHLEIFENBEDINGUNG", 9, "SHEFNEIGNCLIEBDNUG"},
		{"TYPANPASSUNG", 2, "TAYSPSAUNNPG"},
		{"TYPANPASSUNG", 3, "TNSYPUPANASG"},
		{"TYPANPASSUNG", 4, "TAAUYNSNPPSG"},
		{"TYPANPASSUNG", 6, "TPNASNYAPSUG"},
		{"TYPANPASSUNG", 12, "TYPANPASSUNG"},
		{"SCHLEIFENDURCHLAUF", 2, "SDCUHRLCEHILFAEUNF"},
		{"SCHLEIFENDURCHLAUF", 3, "SFCCEHHNLLDAEUUIRF"},
		{"SCHLEIFENDURCHLAUF", 6, "SLFDCACEEUHUHINRLF"},
		{"SCHLEIFENDURCHLAUF", 9, "SHEFNUCLUCLIEDRHAF"},
		{"ROHESSTRINGLITERAL", 2, "RNOGHLEISTSETRRAIL"},
		{"ROHESSTRINGLITERAL", 3, "RTIORTHIEENRSGASLL"},
		{"ROHESSTRINGLITERAL", 6, "RETNIROSRGTAHSILEL"},
		{"ROHESSTRINGLITERAL", 9, "RHSTIGIEAOESRNLTRL"},
		{"HELLOWORLDPROGRAMM", 2, "HDEPLRLOOGWROARMLM"},
		{"HELLOWORLDPROGRAMM", 3, "HOOERGLLRLDAOPMWRM"},
		{"HELLOWORLDPROGRAMM", 6, "HLODOAEORPGMLWLRRM"},
		{"HELLOWORLDPROGRAMM", 9, "HLOOLPORMELWRDRGAM"},
		{"EINHOHESMASSANSICHERHEIT", 1, "EINHOHESMASSANSICHERHEIT"},
		{"EINHOHESMASSANSICHERHEIT", 2, "EAINNSHIOCHHEESRMHAESIST"},
		{"EINHOHESMASSANSICHERHEIT", 3, "EMCIAHNSEHSROAHHNEESISIT"},
		{"EINHOHESMASSANSICHERHEIT", 4, "EEAEISNRNMSHHAIEOSCIHSHT"},
		{"EINHOHESMASSANSICHERHEIT", 6, "EOMACHIHANHENESSEIHSSIRT"},
		{"EINHOHESMASSANSICHERHEIT", 8, "EHEAAIEEIOSSNCRINHMSSHHT"},
		{"EINHOHESMASSANSICHERHEIT", 12, "ENOEMSASCEHIIHHSASNIHRET"},
		{"PARAMETERDEKLARATION", 2, "PEAKRLAAMREATTEIRODN"},
		{"PARAMETERDEKLARATION", 4, "PEEAATKTRELIARAOMDRN"},
		{"PARAMETERDEKLARATION", 5, "PMRLTAEDAIRTEROAEKAN"},
		{"PARAMETERDEKLARATION", 10, "PRMTRELRTOAAEEDKAAIN"},
		{"MEHRDIMENSIONALEARRAYS", 2, "MOENHARLDEIAMRERNASYIS"},
		{"MEHRDIMENSIONALEARRAYS", 11, "MHDMNINLARYERIESOAERAS"},
		{"DEREFERENZIERUNGSOPERATOR", 5, "DEIGRERESAREROTENUPOFZNER"},
		{"VIELEEINFACHEANWEISUNGEN", 1, "VIELEEINFACHEANWEISUNGEN"},
		{"VIELEEINFACHEANWEISUNGEN", 2, "VEIAENLWEEEIISNUFNAGCEHN"},
		{"VIELEEINFACHEANWEISUNGEN", 3, "VFEIAIECSLHUEENEAGINENWN"},
		{"VIELEEINFACHEANWEISUNGEN", 4, "VIESINAUEFNNLAWGECEEEHIN"},
		{"VIELEEINFACHEANWEISUNGEN", 6, "VEFEENIEAAIGEICNSELNHWUN"},
		{"VIELEEINFACHEANWEISUNGEN", 8, "VLIAEWSGIENCAEUEEEFHNINN"},
		{"VIELEEINFACHEANWEISUNGEN", 12, "VEEIFCENESNEILENAHAWIUGN"},
	}
	for _, tt := range tests {
		got1 := encrypt(tt.m, tt.d)
		if got1 != tt.want {
			t.Errorf("encrypt(%v,%v) = %v, want %v", tt.m, tt.d, got1, tt.want)
		}
		got2 := decrypt(tt.want, tt.d)
		if got2 != tt.m {
			t.Errorf("decrypt(%v,%v) = %v, want %v", tt.want, tt.d, got2, tt.m)
		}
	}
}
