package main

import "math/rand"

// rndWort gibt ein zufälliges Wort aus einer Liste von Wörtern zurück.
func rndWort() string {
	// Anmerkung:
	// wir verwenden hier ein Array für die Wortliste, aus der ein
	// Wort zufällig ausgewählt wird. Arrays wurden zum Zeitpunkt
	// der Aufgabenstellung noch nicht im Kurs eingeführt.
	wortliste := [...]string{
		"Tieflieger",
		"Golang",
		"Donaudampfschiffahrtsgesellschaft",
		"Abbruchbedingung",
		"Abschlusszeichen",
		"Additionsoperator",
		"Adresse",
		"Adressoperator",
		"Anweisung",
		"Argument",
		"Array",
		"Ausdruck",
		"Auswertung",
		"Auswertungsreihenfolge",
		"Bezeichner",
		"Block",
		"Blockkommentar",
		"Boolean",
		"Datentyp",
		"Deklaration",
		"Deklarationsoperator",
		"Dereferenzierung",
		"Dereferenzierungsoperator",
		"Dezimalzahl",
		"Divisionsoperator",
		"Ellipse",
		"Endlosschleife",
		"Ergebnistyp",
		"Exponent",
		"Flag",
		"Funktionsdeklaration",
		"Funktionsrumpf",
		"Funktionsaufruf",
		"Funktionsdeklaration",
		"Genauigkeit",
		"Gleichheitsoperator",
		"Gleitkommazahlen",
		"Hexadezimalzahl",
		"Index",
		"Infixnotation",
		"Klammerung",
		"Konkatenationsoperator",
		"Konstante",
		"Konstantendeklaration",
		"Laufvariable",
		"Lebenszeit",
		"Leerraum",
		"Mantisse",
		"Matrix",
		"Mindestbreite",
		"Multiplikationsoperator",
		"Nachkommastellen",
		"Negationsoperator",
		"Normalisierung",
		"Oktalzahl",
		"Operator",
		"Paket",
		"Paketklausel",
		"Parameter",
		"Parameterdeklaration",
		"Programmelemente",
		"Referenzen",
		"Rundungsfehler",
		"Schleife",
		"Schleifenbedingung",
		"Schleifendurchlauf",
		"Schleifenrumpf",
		"Seiteneffekt",
		"Semikolon",
		"Separatorzeichen",
		"Sichtbarkeit",
		"Signatur",
		"Speicheradresse",
		"Speicherleck",
		"Standardformat",
		"Standardtyp",
		"String",
		"Substring",
		"Subtraktionsoperator",
		"Teilausdruck",
		"Typanpassung",
		"Typkonvertierung",
		"Ungleichheitsoperator",
		"Variable",
		"Variablendeklaration",
		"Verben",
		"Vergleichsoperatoren",
		"Vorzeichen",
		"Wert",
		"whitespace",
		"Wiederholungsanweisung",
		"Zeichenkette",
		"Zeiger",
		"Zeilenkommentar",
		"Zuweisung",
		"Zuweisungsoperator",
		"Zweierkomplement",
	}
	return wortliste[rand.Intn(len(wortliste))]
}
